### ISSUE TITLE
integrity error

### ISSUE THREAD

**Issue by runyaga** [ptahproject/ptahcrowd#1]
ptah_minicms from master
ptah_crowd from master

attempt to login w/ admin/12345; fail.

```
Traceback (most recent call last):
  File "c:\ptah\birthday\lib\site-packages\pyramid_debugtoolbar-0.9.7-py2.7.egg\pyramid_debugtoolbar\panels\performance.py", line 69, in noresource_timer_handler
    result = handler(request)
  File "c:\ptah\birthday\lib\site-packages\pyramid\tweens.py", line 20, in excview_tween
    response = handler(request)
  File "c:\ptah\birthday\lib\site-packages\pyramid_tm-0.3-py2.7.egg\pyramid_tm\__init__.py", line 61, in tm_tween
    response = handler(request)
  File "c:\ptah\birthday\lib\site-packages\pyramid_exclog-0.5-py2.7.egg\pyramid_exclog\__init__.py", line 40, in exclog_tween
    return handler(request)
  File "c:\ptah\birthday\lib\site-packages\pyramid\router.py", line 164, in handle_request
    response = view_callable(context, request)
  File "c:\ptah\birthday\lib\site-packages\pyramid\config\views.py", line 148, in _owrapped_view
    response = view(context, request)
  File "c:\ptah\birthday\lib\site-packages\pyramid\config\views.py", line 315, in rendered_view
    result = view(context, request)
  File "c:\ptah\birthday\src\ptah\ptah\form\form.py", line 98, in _class_view
    res = inst.render_update()
  File "c:\ptah\birthday\src\ptah\ptah\form\form.py", line 236, in render_update
    result = self.update()
  File "c:\ptah\birthday\src\ptah_crowd\ptah_crowd\login.py", line 91, in update
    return super(LoginForm, self).update()
  File "c:\ptah\birthday\src\ptah\ptah\form\form.py", line 229, in update
    return self.actions.execute()
  File "c:\ptah\birthday\src\ptah\ptah\form\button.py", line 159, in execute
    result = action(self.form)
  File "c:\ptah\birthday\src\ptah\ptah\form\button.py", line 60, in __call__
    return getattr(context, self.actionName)()
  File "c:\ptah\birthday\src\ptah_crowd\ptah_crowd\login.py", line 48, in handleLogin
    info = ptah.auth_service.authenticate(data)
  File "c:\ptah\birthday\src\ptah\ptah\authentication.py", line 193, in authenticate
    if not checker(info):
  File "c:\ptah\birthday\src\ptah_crowd\ptah_crowd\validation.py", line 27, in validationAndSuspendedChecker
    props = get_properties(info.__uri__)
  File "c:\ptah\birthday\src\ptah_crowd\ptah_crowd\memberprops.py", line 17, in get_properties
    Session.flush()
  File "build\bdist.win32\egg\sqlalchemy\orm\scoping.py", line 113, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "build\bdist.win32\egg\sqlalchemy\orm\session.py", line 1547, in flush
    self._flush(objects)
  File "build\bdist.win32\egg\sqlalchemy\orm\session.py", line 1616, in _flush
    flush_context.execute()
  File "build\bdist.win32\egg\sqlalchemy\orm\unitofwork.py", line 328, in execute
    rec.execute(self)
  File "build\bdist.win32\egg\sqlalchemy\orm\unitofwork.py", line 472, in execute
    uow
  File "build\bdist.win32\egg\sqlalchemy\orm\mapper.py", line 2291, in _save_obj
    execute(statement, params)
  File "build\bdist.win32\egg\sqlalchemy\engine\base.py", line 1405, in execute
    params)
  File "build\bdist.win32\egg\sqlalchemy\engine\base.py", line 1538, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build\bdist.win32\egg\sqlalchemy\engine\base.py", line 1646, in _execute_context
    context)
  File "build\bdist.win32\egg\sqlalchemy\engine\base.py", line 1639, in _execute_context
    context)
  File "build\bdist.win32\egg\sqlalchemy\engine\default.py", line 330, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) ptah_crowd_memberprops.uri may not be NULL u'INSERT INTO ptah_crowd_memberprops (joined, validated, suspended, data) VALUES (?, ?, ?, ?)' ('2011-12-20 23:03:56.740000', 0, 0, '{}')
```

**Comment by fafhrd91** [comment]
fixed
